export const skillRegistryAbi = [
  {
    inputs: [{ internalType: 'address', name: 'initialOwner', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'EmptyMetadataCID', type: 'error' },
  { inputs: [], name: 'EmptyName', type: 'error' },
  { inputs: [], name: 'NotOwner', type: 'error' },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    name: 'SkillNotFound',
    type: 'error',
  },
  { inputs: [], name: 'ZeroAddress', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' }, { indexed: false, internalType: 'bool', name: 'active', type: 'bool' }],
    name: 'SkillActiveToggled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'provider', type: 'address' },
      { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      { indexed: false, internalType: 'string', name: 'metadataCID', type: 'string' },
      { indexed: false, internalType: 'bytes32', name: 'systemPromptHash', type: 'bytes32' },
      { indexed: false, internalType: 'uint256', name: 'pricePerRun', type: 'uint256' },
    ],
    name: 'SkillCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'id', type: 'uint256' },
      { indexed: false, internalType: 'string', name: 'metadataCID', type: 'string' },
      { indexed: false, internalType: 'bytes32', name: 'systemPromptHash', type: 'bytes32' },
      { indexed: false, internalType: 'uint256', name: 'pricePerRun', type: 'uint256' },
    ],
    name: 'SkillUpdated',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'metadataCID', type: 'string' },
      { internalType: 'bytes32', name: 'systemPromptHash', type: 'bytes32' },
      { internalType: 'uint256', name: 'pricePerRun', type: 'uint256' },
    ],
    name: 'createSkill',
    outputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'id', type: 'uint256' },
      { internalType: 'string', name: 'metadataCID', type: 'string' },
      { internalType: 'bytes32', name: 'systemPromptHash', type: 'bytes32' },
      { internalType: 'uint256', name: 'pricePerRun', type: 'uint256' },
    ],
    name: 'updateSkill',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    name: 'toggleActive',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    name: 'getSkill',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'id', type: 'uint256' },
          { internalType: 'address', name: 'provider', type: 'address' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'metadataCID', type: 'string' },
          { internalType: 'bytes32', name: 'systemPromptHash', type: 'bytes32' },
          { internalType: 'uint256', name: 'pricePerRun', type: 'uint256' },
          { internalType: 'bool', name: 'active', type: 'bool' },
          { internalType: 'uint64', name: 'createdAt', type: 'uint64' },
        ],
        internalType: 'struct SkillRegistry.Skill',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSkills',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'provider', type: 'address' }],
    name: 'skillsByProvider',
    outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
